package amoji_map

var Amojis = map[string]interface{}{
	"acid":            "⊂(◉‿◉)つ",
	"arrow":           "»",
	"arrowleft":       "«",
	"afraid":          "(ㆆ _ ㆆ)",
	"alpaca":          "(◕(‘人‘) ◕)",
	"alpha":           "α",
	"angel":           "☜(⌒▽⌒)☞",
	"angry":           "(⋟﹏⋞)",
	"arrowhead":       "⤜(ⱺ ʖ̯ⱺ)⤏",
	"awkward":         "•͡˘㇁•͡˘",
	"butt":            "(‿|‿)",
	"bat":             "/|\\ ^._.^ /|\\",
	"bear":            "ʕ·͡ᴥ·ʔ",
	"beardab":         "／ʕ •ᴥ•ʔ／",
	"bearhug":         "ʕっ•ᴥ•ʔっ",
	"beta":            "β",
	"bitcoin":         "₿",
	"bird":            "⋛ ⋋( ‘Θ’)⋌⋚ ",
	"blush":           "(˵ ͡° ͜ʖ ͡°˵)",
	"boobs":           "( . Y . )",
	"boombox":         "♫♪.ıll|̲̅̅●̲̅̅|̲̅̅=̲̅̅|̲̅̅●̲̅̅|llı.♫♪",
	"bored":           "(-_-)",
	"bribe":           "( •͡˘ _•͡˘)ノð",
	"bubbles":         "( ˘ ³˘)ノ°ﾟº❍｡",
	"butterfly":       "ƸӜƷ",
	"cat":             "(= ФェФ=)",
	"cheer":           "※\\(^o^)/※",
	"cheerleader":     "✽ -( ˘▽ ˘ )/✽ ",
	"chubby":          "╭(ʘ̆~◞౪◟~ʘ̆)╮",
	"celebrate":       "٩(^‿^)۶",
	"gang":            "༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ",
	"coffee":          "c[_]",
	"cool":            "(⌐■_■)",
	"copyright":       "©",
	"confused":        "O_o",
	"creep":           "ԅ(≖‿≖ԅ)",
	"cross":           "†",
	"cry":             "(╥﹏╥)",
	"cry2":            "(╥_╥)",
	"crywave":         "( ╥﹏╥) ノシ",
	"cute":            "(｡◕‿‿◕｡)",
	"cuteflower":      "(❁ ≧ ᴗ≦ )",
	"curious":         "( ￢ε￢　)",
	"dab":             "ヽ( •_)ᕗ",
	"damnyou":         "(ᕗ ͠° ਊ ͠° )ᕗ",
	"dance":           "ᕕ(⌐■_■)ᕗ ♪♪",
	"dancing":         "♪ ┏(°.°)┛┗(°.°)┓┗(°.°)┛ ♪ ",
	"dashleft":        "三二。。",
	"dashright":       "。。二三",
	"dead":            "x⸑x",
	"depressed":       "(︶︹︶)",
	"derp":            "☉ ‿ ⚆ ",
	"dj":              "d[-_-]b",
	"dog":             "(◕ᴥ◕ʋ)",
	"idc":             "(- ʖ̯-)",
	"dontwant":        "ヽ(｀Д´)ﾉ",
	"dollar":          "[̲̅$̲̅(̲̅1)̲̅$̲̅]",
	"dope":            "(^_^)",
	"doubletableflip": "┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻",
	"duckface":        "(・3・)",
	"duel":            "ᕕ(╭ರ╭ ͟ʖ╮•́)⊃¤=(————-",
	"duh":             "(≧︿≦)",
	"dunno":           "¯\\(°_o)/¯",
	"drool":           "⌐(ಠ۾ಠ)¬",
	"emptystar":       "☆ ",
	"endure":          "(҂◡_◡) ᕤ",
	"epsilon":         "ɛ",
	"euro":            "€",
	"evil":            "ψ(｀∇´)ψ",
	"eyebrows":        "ʕʘ̅͜ʘ̅ʔ",
	"excited":         "(ﾉ◕ヮ◕)ﾉ*ﾟ",
	"execution":       "(⌐■_■)︻╦╤─  (╥﹏╥)",
	"facepalm":        "( >ლ )",
	"fangirl":         "(ノ^о^)ノ",
	"fart":            "(ˆ⺫ˆ๑)",
	"fight":           "(ง •̀_•́)ง",
	"finn":            "| (• ◡•)|",
	"fish":            "¯·.¸><(((º>",
	"flex":            "ᕙ(`▽´)ᕗ",
	"flower":          "(✿ ◠‿◠)",
	"fly":             "─=≡Σ((( つ◕ل͜◕)つ",
	"friendflip":      "(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)",
	"frown":           "(ღ˘⌣˘ღ)",
	"fuckoff":         "୧༼ಠ益ಠ╭∩╮༽",
	"fuckyou":         "┌П┐(ಠ_ಠ)",
	"gentleman":       "ಠ_ರೃ<",
	"ghast":           "= _ =",
	"ghost":           "༼ つ ╹ ╹ ༽つ",
	"giddy":           "(๑˃ᴗ˂)",
	"gift":            "(´・ω・)っ由",
	"gimme":           "༼ つ ◕_◕ ༽つ",
	"givemeyourmoney": "(•-•)⌐",
	"glitter":         "(*・‿・)ノ⌒*:･ﾟ✧ ",
	"glasses":         "(⌐ ͡■ ͜ʖ ͡■)",
	"glassesoff":      "( ͡° ͜ʖ ͡°)ﾉ⌐■-■",
	"glitterderp":     "(ﾉ☉ヮ⚆)ﾉ ⌒*:･ﾟ",
	"gloomy":          "(_゜_゜_)",
	"gotit":           "(☞ ﾟ∀ﾟ)☞ ",
	"greet":           "( ´◔ ω◔`) ノシ",
	"gun":             "︻╦╤─",
	"hadouken":        "༼つಠ益ಠ༽つ ─=≡ΣO))",
	"hammerandsickle": "☭",
	"handleft":        "☜ ",
	"handright":       "☞ ",
	"happy":           "٩( ๑╹ ꇴ╹)۶",
	"happystroll":     "ᕕ( ᐛ )ᕗ",
	"happywizard":     "(˵╹◡╹)━☆ ",
	"heart":           "♥ ",
	"hello":           "(ʘ‿ʘ)╯",
	"help":            "\\(°Ω°)/",
	"highfive":        "._.)/\\(._.",
	"hit":             "( ｀皿´)｡ﾐ/",
	"homer":           "(_8^(J))",
	"house":           "|̲̲̲͡͡͡ ̲▫̲͡ ̲̲̲͡͡π̲̲͡͡ ̲̲͡▫̲̲͡͡ ̲|̡̡̡ ̡ ̴̡ ",
	"hug":             "(づ｡◕‿‿◕｡)づ",
	"hug2":            "(っ◕‿◕)っ",
	"iknowright":      "┐｜･ิω･ิ#｜┌",
	"infinity":        "∞",
	"inlove":          "(っ´ω`c)♡ ",
	"internet":        "ɪɴᴛᴇʀɴᴇᴛ",
	"internethappy":   "ଘ(੭*ˊᵕˋ)੭* ̀ˋ ɪɴᴛᴇʀɴᴇᴛ",
	"jake":            "(❍ ᴥ❍ ʋ)",
	"kawai":           "≧ ◡≦ ",
	"keen":            "┬┴┬┴┤Ɵ͆ل͜Ɵ͆ ༽ﾉ",
	"kiahh":           "~\\(≧▽≦)/~",
	"kiss":            "(づ ￣ ³￣)づ",
	"kittycat":        "=^..^=",
	"kirby":           "(ง︡'-'︠)ง",
	"kirbydance":      "<(''<)<( ' ' )>(> '')>",
	"knife":           ")xxxx[;;;;;;;>",
	"lambda":          "λ",
	"left":            "←",
	"lenny":           "( ͡° ͜ʖ ͡°)",
	"lennyfight":      "(ง ͠° ͟ʖ ͡°)ง",
	"lennyflip":       "(ノ ͡° ͜ʖ ͡°ノ)   ︵ ( ͜。 ͡ʖ ͜。)",
	"lennyshrug":      "¯\\_( ͡° ͜ʖ ͡°)_/¯",
	"lennysir":        "( ಠ ͜ʖ ರೃ)",
	"lennystrong":     "ᕦ( ͡° ͜ʖ ͡°)ᕤ",
	"lennywizard":     "╰( ͡° ͜ʖ ͡° )つ──☆ *:・ﾟ",
	"lol":             "L(° O °L)",
	"look":            "( ಡ _ಡ )☞ ",
	"lonely":          "<(°^°<0)",
	"loud":            "ᕦ(⩾﹏⩽)ᕥ",
	"love":            "♥ ‿♥ ",
	"lovebear":        "ʕ♥ ᴥ♥ ʔ",
	"lumpy":           "꒰ ꒡⌓꒡꒱",
	"luv":             "-` ღ ´-",
	"magic":           "ヽ(｀Д´)⊃━☆ ﾟ. * ･ ｡ﾟ",
	"magicflip":       "(/¯◡ ‿ ◡)/¯ ~ ┻━┻",
	"mantears":        "ಥ_ಥ",
	"meatwad":         "{٩ಠಠ}",
	"meep":            "\\(°^°)/",
	"meh":             "ಠ_ಠ",
	"mistyeyes":       "ಡ _ಡ ",
	"monster":         "༼ ༎ຶ ෴ ༎ຶ༽",
	"mouse":           "<:3 )~~",
	"mustachewizard":  "(⍤෴ ⍤)━☆ ﾟ.*･｡ﾟ",
	"needle":          "┌(◉ ͜ʖ◉)つ┣▇▇▇═──",
	"nerd":            "(⌐⊙ _⊙ )",
	"nice":            "( ͡° ͜ °)",
	"no":              "-_-",
	"nom":             "(っˆڡˆς)",
	"note":            "♫ ",
	"racecar":         "\\ō͡≡o˞̶",
	"rat":             "~(__^>",
	"nyan":            "~=[,,_,,]:3",
	"ohshit":          "( º﹃º )",
	"omega":           "Ω",
	"omg":             "◕_◕",
	"orly":            "(눈_눈)",
	"ohyou":           "(◞థ౪థ)ᴖ",
	"panic":           "⊂(⊙ д⊙ )つ",
	"party":           "♪ ヽ( ⌒o⌒)人(⌒-⌒ )v ♪ ",
	"peace":           "(-‿-)✌ ",
	"pi":              "π",
	"pig":             "^(*(oo)*)^",
	"pingpong":        "( •_•)O*¯`·.¸.·´¯`°Q(•_• )",
	"pleased":         "(˶‾᷄ ⁻̫ ‾᷅˵)",
	"point":           "(☞ ﾟヮﾟ)☞ ",
	"pooh":            "ʕ •́؈•̀)",
	"pound":           "£",
	"power":           "ᕙ(`▽´)ᕗ",
	"pray":            "八(＾□ ＾*)",
	"praise":          "(☝ ՞ਊ ՞)☝",
	"punch":           "O=('-'Q)",
	"mad":             "t(ಠ益ಠt)",
	"rageflip":        "(ノಠ益ಠ)ノ彡┻━┻",
	"rainbowcat":      "(=^･ｪ･^=))ﾉ彡☆ ",
	"really":          "ò_ô",
	"right":           "→",
	"riot":            "୧༼ಠ益ಠ༽୨",
	"rolleyes":        "(◔_◔)",
	"rose":            "✿ڿڰۣ—",
	"robot":           "d[ o_0 ]b",
	"run":             "(╯°□°)╯",
	"run2":            "└(>ω<。)┐ -=≡",
	"rush":            "。。ミヽ(。＞＜)ノ",
	"sad":             "(〒﹏〒)",
	"sad2":            "( ಥ -ಥ )",
	"sad3":            "ε(´סּ︵סּ`)з",
	"sadlenny":        "( ͡° ʖ̯ ͡°)",
	"sadpraying":      "(人´口`)",
	"serious":         "(ಠ_ಠ)",
	"seriously":       "(⊙ _⊙ )",
	"shout":           "╚(•⌂•)╝",
	"shrug":           "¯\\_(ツ)_/¯",
	"shy":             "=^_^=",
	"sigma":           "Σ",
	"smile":           "ツ",
	"smirk":           "¬‿¬",
	"smug":            "(‾⌣‾)",
	"sob":             "(;´༎ຶД༎ຶ`)",
	"sorry":           "(*_ _)人",
	"sleep":           "(-.-) Zzz",
	"sparkle":         "*✧ ･ﾟ",
	"sparkle2":        "･ﾟ✧ *:･ﾟ",
	"spider":          "///\\oo/\\\\\\",
	"spy":             "┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ ̿",
	"squid":           "くコ:彡",
	"star":            "★ ",
	"strong":          "ᕙ(⇀‸↼‶)ᕗ",
	"stern":           "( ･ิ _ゝ･ิ)",
	"sun":             "☀ ",
	"surprised":       "(๑•́ヮ•̀๑)",
	"surrender":       "\\_(-_-)_/",
	"stalker":         "┬┴┬┴┤(･_├┬┴┬┴",
	"snowman":         "☃",
	"swag":            "(̿▀̿‿ ̿▀̿ ̿)",
	"sweat":           "(-_- ;)",
	"sword":           "o(===||:::::::::::>",
	"tabledown":       "┬─┬  ノ( ゜-゜ノ)",
	"tableflip":       "(ノ ゜Д゜)ノ ︵ ┻━┻",
	"tada":            "⊂(o‿o)つ",
	"tau":             "τ",
	"tears":           "(ಥ﹏ಥ)",
	"tear":            "(˘_˘٥)",
	"teddy":           "ˁ(⦿ ᴥ⦿ )ˀ",
	"terrorist":       "୧༼ಠ益ಠ༽︻╦╤─",
	"tosscomputer":    "(╯°□°）╯︵ [_]||",
	"thanks":          "\\(^-^)/",
	"this":            "( ͡° ͜ʖ ͡°)_//¯",
	"tiefighter":      "|=-(¤)-=|",
	"tired":           "(=____=)",
	"toldyouso":       "☜ (꒡⌓꒡)",
	"toogood":         "ᕦ(òᴥó)ᕥ",
	"tm":              "™",
	"triangle":        "▲",
	"trumpet":         "-=iii=<()",
	"unflip":          "┬──┬ ノ(ò_óノ)",
	"victory":         "(๑•̀ㅂ•́)ง✧ ",
	"wat":             "(ÒДÓױ)",
	"wave":            "( * ^ *) ノシ",
	"wand":            "━☆ ﾟ.*･｡ﾟ",
	"what":            "ლ(ಠ益ಠლ)╯",
	"whistle":         "(っ^з^)♪ ♬ ",
	"woa":             "(◉ o ◉)/",
	"whoa":            "(°o•)",
	"whoosh":          "。。。ミ",
	"why":             "ლ(`◉◞౪◟◉‵ლ)",
	"woo":             "＼(＾O＾)／",
	"wink":            "(˵⪰◡•）",
	"wizard":          "(∩｀-´)⊃━☆ ﾟ.*･｡ﾟ",
	"yay":             "\\( ﾟヮﾟ)/",
	"yes":             "(•̀ᴗ•́)و",
	"yen":             "¥",
	"yingyang":        "☯ ",
	"yolo":            "Yᵒᵘ Oᶰˡʸ Lᶤᵛᵉ Oᶰᶜᵉ",
	"yuno":            "(屮ﾟДﾟ)屮 Y U NO",
	"zen":             "⊹╰(⌣ʟ⌣)╯⊹",
	"zoidberg":        "(V) (°,,,,°) (V)",
	"zombie":          "[¬º-°]¬",
	"zoom":            "(’ω’ ⊃)⊃三二一",
}
